name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Build
        env:
            DEBEMAIL: "${{ secrets.DEBEMAIL }}"
            DEBFULLNAME: "${{ secrets.DEBFULLNAME}}"
            PPA_OWNER: "${{ secrets.PPA_OWNER }}"
        run: |
          docker build .
